name: HCFPlus
main: life.steeze.hcfplus.HCFPlugin
description: Simply HCF
commands:
  faction:
    description: Use factions
    aliases: [f, factions, fac]
permissions:
  hcf.admin:
    default: op
api-version: 1.18
version: 1.18.7
author: ViperCobra
softdepend: [PlaceholderAPI]